### ISSUE TITLE
Introducing a recent survey paper on LLM-based game agents

### ISSUE THREAD

**Issue by Bayi-Hu** [AGI-Edgerunners/LLM-Agents-Papers#14]
Hi!

Thank you for maintaining this valuable resources in the area of building LLM-based agents!

I want to share our recent survey paper named "A Survey on Large Language Model-Based Game Agents" (https://arxiv.org/abs/2404.02039), which mainly focuses on LLM-based game agents and covers six game categories, including adventure, simulation, competition, cooperation, communication and crafting & exploration.

We would be grateful if you would consider including our paper in your paper list. Thank you!

**Comment by LYH-YF** [comment]
great work!
