### ISSUE TITLE
Introducing a new paper on role-playing LLM agents (ACL 2024 Findings)

### ISSUE THREAD

**Issue by ahnjaewoo** [AGI-Edgerunners/LLM-Agents-Papers#18]
Hi, what a fantastic resource for developing intelligent LLM agents!

I wanted to highlight a recent paper presented at ACL 2024 Findings: [TimeChara: Evaluating Point-in-Time Character Hallucination of Role-Playing Large Language Models](https://ahnjaewoo.github.io/timechara).
This study focuses on _assessing hallucinations_ in role-playing LLM agents when they simulate characters **at specific moments in time**.

We would greatly appreciate it if you could consider adding our paper to your survey.
Thanks!

**Comment by LYH-YF** [comment]
Thanks for your recommendation!
I already added it in the Role Playing category.
