### ISSUE TITLE
new paper

### ISSUE THREAD

**Issue by aldopareja** [AGI-Edgerunners/LLM-Agents-Papers#6]
I would add this paper to the benchmarks section.

FANTOM:
A Benchmark for Stress-testing Machine Theory of Mind in Interactions

**Comment by LYH-YF** [comment]
Welcome to add new papers. The least labor-intensive way to add is to add an arxiv abs link of the paper into the corresponding json file under the folder ```papers```. And then submit a pull request.

**Comment by LYH-YF** [comment]
I have added this paper to the benchmark section. Thank you for your suggestion!
